export const states = [
  { name: 'São Paulo', abbreviation: 'SP' },
  { name: 'Rio de Janeiro', abbreviation: 'RJ' },
  { name: 'Minas Gerais', abbreviation: 'MG' },
  { name: 'Espírito Santo', abbreviation: 'ES' },
  { name: 'Paraná', abbreviation: 'PR' },
  { name: 'Santa Catarina', abbreviation: 'SC' },
  { name: 'Rio Grande do Sul', abbreviation: 'RS' },
  { name: 'Mato Grosso do Sul', abbreviation: 'MS' },
  { name: 'Mato Grosso', abbreviation: 'MT' },
  { name: 'Goiás', abbreviation: 'GO' },
  { name: 'Distrito Federal', abbreviation: 'DF' },
  { name: 'Acre', abbreviation: 'AC' },
  { name: 'Amazonas', abbreviation: 'AM' },
  { name: 'Roraima', abbreviation: 'RR' },
  { name: 'Rondônia', abbreviation: 'RO' },
  { name: 'Amapá', abbreviation: 'AP' },
  { name: 'Pará', abbreviation: 'PA' },
  { name: 'Tocantins', abbreviation: 'TO' },
  { name: 'Bahia', abbreviation: 'BA' },
  { name: 'Piauí', abbreviation: 'PI' },
  { name: 'Maranhão', abbreviation: 'MA' },
  { name: 'Ceará', abbreviation: 'CE' },
  { name: 'Rio Grande do Norte', abbreviation: 'RN' },
  { name: 'Paraíba', abbreviation: 'PB' },
  { name: 'Pernambuco', abbreviation: 'PE' },
  { name: 'Alagoas', abbreviation: 'AL' },
  { name: 'Sergipe', abbreviation: 'SE' }

]
